language: node_js
cache:
  yarn: true
  directories:
  - node_modules
matrix:
  fast_finish: true
  include:
  - node_js: '8'
    env: TEST_MODE=normal
  - node_js: '6'
    env: TEST_MODE=normal
  - node_js: '8'
    env:
    - SAUCE_USERNAME=redpanda
    - TEST_MODE=browsers
script:
- if [ "${TEST_MODE}" = "browsers" ]; then npm run test-browsers; fi
- if [ "${TEST_MODE}" = "normal" ];   then npm run test; fi
env:
  global:
    secure: sWF780ipCKXh3b5/h1V7GG9FvNM6h9iUj8J29QMeOcCKPWNT5tyaMOooQxM9oo263meH91go6p5k/rBL+otVoAKZyD/TThbBiKUnKrhra8hoBpqrL9WBx5IQG581vEKlpUiYxyusnhl0+QQHMoKphHqdWP30qD2H+mZV0e+NSmGb/J4VeII32hKuxjUQiKShRd8YN2gmu06Qn9AMDzF93dY+Bl+L+oa+14SZxtz7Q4qd5asHx+NKiDu4AgGBRUpc2kOoZnhtgEk8khSMqc5sM1ZsXHdL6olajemcgkW6O1ICezg5zxLS9fI9Gk5Hn4n/Agpel5lAWyO//avw+OSfLC4ZOWAK7Fu7GI9LUTAC9iB6xztq5u0O2Vkqw4Xit78uEMN8E9p6nLcN6BYeVwPcd1x5SDOJvlsLAofJ0Hdq43EKZ7Um//Fd+BAmufmo+PEQggq+fxgaVI4oQwtex+a3VNQyHeCBF8sT20tPvvwgR24+AZ//2oCGW1CPOXS4aCBKHhVQHNhGwG/gDCoEuFnhZd+DTCqCFdVWWRU6zcDBz6UjriisZ4jy9UicmhfEdbJYymlMN8zk8mnhS9fNjt6IPqUWGhEjQ8zCdadePdpitkKtqQ31tjfEk7PPH1RHgKAZHQewDBd/B1sACF59mJOrclwxxJQdX4y4ThWeMj+AE8U=
