language: node_js
cache:
  yarn: true
  directories:
  - node_modules
matrix:
  fast_finish: true
  include:
  - node_js: '8'
    env: SCRIPT=test
  - node_js: '6'
    env: SCRIPT=test
  - node_js: '8'
    env:
    - SAUCE_USERNAME=redpanda
    - SCRIPT=test-browsers
script:
- if [ "${SCRIPT}" = "test" ]; npm run ${SCRIPT}; fi
- if [ "$TRAVIS_PULL_REQUEST" = "true" -a "${SCRIPT}" = "test-browsers" ]; npm run ${SCRIPT}; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" -a "${SCRIPT}" = "test-browsers" ]; echo 'Only pull requests get browsers testing.' & exit 0; fi
env:
  global:
  - secure: KpA4F+wUWyas5Ymd24jGjxpgispDM2McTwFnGZjylCgNK2aJYSo3RkG7bKKp2p7dEUMqWBhtrgibqvgNUicqpL9wHZ0fCyqeLdYZahRhYBgSqaBFres4IYzHtemYIq51YIBnH3LKvXD2jAEB3OXN3U1fLOr8L7fgYuRaLNB/W3WXgqZEIXUqtI7BBx9rGxvKvSx8iV5kpsf3V1lShCzrHEDvtgYAx4YLsFwwZ9vEO/lmkU8CK90uqJUJwjKULtk8UCoj1EytT8BmhR0b3QqX6oZsUB1FwtdNuL9aWoNzgoZW0CsIvBGuTeevxfZmtGsLKvOQ+TiBOjXvidHVFhNwYKKzoMCo4YkIn6ufQkPe4av3xZO5GoYllY9+dbjJYn9eoUg16lztr6d8+Dwcidaqdq8YfH308ZKUM7sPDHGpgzEkdP+sbAHPWQCpJQh8xmrbrRsUJs8jjWvid9Ct9DiuNJ+s/d+aTlT0gUx1biqvdqQcnuuLSWjf+VXmqOp0WGOaFCjsXRcNnShBJKc5mLqfVmq+2tpeyJS0U5IJlwd/wXv2pdFX82JhxZNWRXRcdshYyC/zWjN2X1m+fRi2xICxwmMhCA4hroPiun7pVenlwbQaFa+736TvW/f8kszrVIMOYap1HDcleZpdax/Cg7Ps6Bbp/MlCJzbxPRlPcjF7r3Q=
  - secure: orB+tC3DfXEOYAIf0Z+TPZGdMOozwv/b1K/9CtxzkG/1+SqyiF7EgYrvnEBYKTeu1Pgqkx/X3Pmc05Rw9eDXa0zg3iuRFM10vZpy4IaK1dLUYZV/17mKqlTyLesbD8sbx4ol+mQYyAJ2rIS121oOJ94zp1wi+J5r4/esdg1m+q4a78d9f4WasyGx9uWYL9P04+O3qZwgnK7zYMvjAtc2RfmNw7Xw1+AvmVioKB4uJX54+LHH4CaHNlhTvyvTNcs9fj39bu1ieTOt5YiN3KCyYU+UJHw5jhpQzpdspXcdUtOZ4FDPRqjVVBeBl8FxfKz9Y2TT88KoHFH6nEYYADAKWxXYYRikZdFheZNZWmx+PADNIukwweN5BeoQwe3+4tQv+c3VDcdBOhtRLa9uetaCBQAJSoN8+R4LSFxG9epUR1KfvNVzHdsvIALuymzDaDUjIlhJaIppDtDZ/It6Ob+1u75dgQO22RM9+2n49ViboYMyaBFr/TrKoWDZ5SWz9cINM/esznjiQzppXDU+ycjE7bqK1IulErJTAdr6tUcgQfA0PFRLr3ieb99ZT2x4PQWaRKswqHCiypq47fMM73JqT1K8kcr0v9NHCsSDiOB7/mLFvzcuup3v0pn/ivBhKiQ4gOnEDTFj2iyB8seBacdpyjw9sjAMlDjjHbQusQAXyb0=
