language: node_js
cache:
  yarn: true
  directories:
    - node_modules
matrix:
  fast_finish: true
  include:
    - node_js: "8"
      env: SCRIPT=test
    - node_js: "6"
      env: SCRIPT=test
    - node_js: "4"
      env: SCRIPT=test
script:
  - "npm run ${SCRIPT}"
